name: Assemble Debug APK

env:
  GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dkotlin.compiler.execution.strategy=in-process'
  JAVA_VERSION: 11
on:
  push:
    branches:
      - 'master'
permissions:
  contents: read
jobs:
  build:
    name: Assemble Debug APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'adopt'
      - name: Assemble APK
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: assembleDebug
      - name: Printing Signing Report
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: signingReport
      - name: Upload APK to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: examplekt-debug.apk
          path: examplekt/build/outputs/apk/debug/examplekt-debug.apk
  release:
    name: Creating release
    needs: [ build ]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Read version.txt file
        id: version-file
        run: echo "::set-output name=version::$(cat version.txt)"
      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: v${{ steps.version-file.outputs.version }}
          prerelease: true
          draft: true